import { PhaseInfo, Lesson, PhonemeCard } from "@/types/curriculum";
import { phase1Lessons } from "./lessons/phase1";
import { phase2Lessons } from "./lessons/phase2";
import { phase3Lessons } from "./lessons/phase3";
import { phase4Lessons } from "./lessons/phase4";

export const PHASES: PhaseInfo[] = [
  {
    phase: 1,
    title: "Pre-Reading Skills",
    description: "Phonological & Phonemic Awareness",
    lessonRange: [1, 5],
    color: "#FF6B9D",
  },
  {
    phase: 2,
    title: "The Alphabetic Principle",
    description: "Letter-Sounds & CVC Words",
    lessonRange: [6, 25],
    color: "#4ECDC4",
  },
  {
    phase: 3,
    title: "Expanding the Code",
    description: "Digraphs, Blends & Patterns",
    lessonRange: [26, 45],
    color: "#FFD93D",
  },
  {
    phase: 4,
    title: "Advanced Decoding",
    description: "VCe, Syllables & Morphology",
    lessonRange: [46, 55],
    color: "#A78BFA",
  },
];

export const ALL_PHONEME_CARDS: PhonemeCard[] = [
  // VOWELS - Organized in Vowel Valley shape
  // Long e (high front)
  {
    phoneme: "/ē/",
    graphemes: ["ee", "e_e", "e", "ea", "ey", "y", "ie", "ei"],
    anchorWord: "bee",
    anchorImage: "🐝",
    category: "vowel",
    subcategory: "long_e",
    unlocked: false,
  },
  // Short i
  {
    phoneme: "/ĭ/",
    graphemes: ["i", "y"],
    anchorWord: "igloo",
    anchorImage: "🏔️",
    category: "vowel",
    subcategory: "short_i",
    unlocked: false,
  },
  // Long a
  {
    phoneme: "/ā/",
    graphemes: ["a", "a_e", "ai", "ay", "ei", "ey", "ea"],
    anchorWord: "alien",
    anchorImage: "👽",
    category: "vowel",
    subcategory: "long_a",
    unlocked: false,
  },
  // Short e
  {
    phoneme: "/ĕ/",
    graphemes: ["e", "ea"],
    anchorWord: "egg",
    anchorImage: "🥚",
    category: "vowel",
    subcategory: "short_e",
    unlocked: false,
  },
  // Short a
  {
    phoneme: "/ă/",
    graphemes: ["a"],
    anchorWord: "apple",
    anchorImage: "🍎",
    category: "vowel",
    subcategory: "short_a",
    unlocked: false,
  },
  // Long i
  {
    phoneme: "/ī/",
    graphemes: ["i", "i_e", "ie", "y", "igh", "ig"],
    anchorWord: "ice",
    anchorImage: "🧊",
    category: "vowel",
    subcategory: "long_i",
    unlocked: false,
  },
  // Short o
  {
    phoneme: "/ŏ/",
    graphemes: ["o", "a"],
    anchorWord: "octopus",
    anchorImage: "🐙",
    category: "vowel",
    subcategory: "short_o",
    unlocked: false,
  },
  // Short u
  {
    phoneme: "/ŭ/",
    graphemes: ["u"],
    anchorWord: "umbrella",
    anchorImage: "☂️",
    category: "vowel",
    subcategory: "short_u",
    unlocked: false,
  },
  // aw sound
  {
    phoneme: "/aw/",
    graphemes: ["aw", "au", "al"],
    anchorWord: "paw",
    anchorImage: "🐾",
    category: "vowel",
    subcategory: "aw",
    unlocked: false,
  },
  // Long o
  {
    phoneme: "/ō/",
    graphemes: ["o", "o_e", "ow", "oa", "oe"],
    anchorWord: "oval",
    anchorImage: "⭕",
    category: "vowel",
    subcategory: "long_o",
    unlocked: false,
  },
  // oo (book)
  {
    phoneme: "/oo/",
    graphemes: ["oo", "u"],
    anchorWord: "book",
    anchorImage: "📖",
    category: "vowel",
    subcategory: "oo_short",
    unlocked: false,
  },
  // Long u (ue)
  {
    phoneme: "/ū/",
    graphemes: ["ue", "u_e", "ew", "ew", "u"],
    anchorWord: "unicorn",
    anchorImage: "🦄",
    category: "vowel",
    subcategory: "long_u",
    unlocked: false,
  },
  // yoo sound
  {
    phoneme: "/yū/",
    graphemes: ["u", "u_e", "ue"],
    anchorWord: "music",
    anchorImage: "🎵",
    category: "vowel",
    subcategory: "yoo",
    unlocked: false,
  },
  // oi/oy
  {
    phoneme: "/oi/",
    graphemes: ["oi", "oy"],
    anchorWord: "coin",
    anchorImage: "🪙",
    category: "vowel",
    subcategory: "oi",
    unlocked: false,
  },
  // ou/ow
  {
    phoneme: "/ou/",
    graphemes: ["ou", "ow"],
    anchorWord: "cloud",
    anchorImage: "☁️",
    category: "vowel",
    subcategory: "ou",
    unlocked: false,
  },
  // er/ir/ur
  {
    phoneme: "/er/",
    graphemes: ["er", "ir", "ur", "or"],
    anchorWord: "bird",
    anchorImage: "🐦",
    category: "vowel",
    subcategory: "r_controlled_er",
    unlocked: false,
  },
  // ar
  {
    phoneme: "/ar/",
    graphemes: ["ar", "a"],
    anchorWord: "barn",
    anchorImage: "🏚️",
    category: "vowel",
    subcategory: "r_controlled_ar",
    unlocked: false,
  },
  // or
  {
    phoneme: "/or/",
    graphemes: ["or", "ore", "oar", "our", "oor"],
    anchorWord: "fork",
    anchorImage: "🍴",
    category: "vowel",
    subcategory: "r_controlled_or",
    unlocked: false,
  },
  // schwa
  {
    phoneme: "/ə/",
    graphemes: ["a", "e", "i", "o", "u"],
    anchorWord: "banana",
    anchorImage: "🍌",
    category: "vowel",
    subcategory: "schwa",
    unlocked: false,
  },

  // CONSONANTS - Organized by manner and place of articulation
  // STOPS
  {
    phoneme: "/p/",
    graphemes: ["p", "pp"],
    anchorWord: "pig",
    anchorImage: "🐷",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/b/",
    graphemes: ["b", "bb"],
    anchorWord: "ball",
    anchorImage: "⚽",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/t/",
    graphemes: ["t", "tt", "ed"],
    anchorWord: "tiger",
    anchorImage: "🐯",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/d/",
    graphemes: ["d", "dd", "ed"],
    anchorWord: "dog",
    anchorImage: "🐕",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/k/",
    graphemes: ["c", "k", "ck", "ch", "qu"],
    anchorWord: "cat",
    anchorImage: "🐱",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/g/",
    graphemes: ["g", "gg", "gh", "gu", "gue"],
    anchorWord: "goat",
    anchorImage: "🐐",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  // AFFRICATES
  {
    phoneme: "/ch/",
    graphemes: ["ch", "tch"],
    anchorWord: "cheese",
    anchorImage: "🧀",
    category: "consonant",
    subcategory: "affricate",
    unlocked: false,
  },
  {
    phoneme: "/j/",
    graphemes: ["j", "g", "dge", "ge"],
    anchorWord: "jam",
    anchorImage: "🍓",
    category: "consonant",
    subcategory: "affricate",
    unlocked: false,
  },
  // NASALS
  {
    phoneme: "/m/",
    graphemes: ["m", "mm", "mb"],
    anchorWord: "moon",
    anchorImage: "🌙",
    category: "consonant",
    subcategory: "nasal",
    unlocked: false,
  },
  {
    phoneme: "/n/",
    graphemes: ["n", "nn", "kn", "gn"],
    anchorWord: "nest",
    anchorImage: "🪺",
    category: "consonant",
    subcategory: "nasal",
    unlocked: false,
  },
  {
    phoneme: "/ng/",
    graphemes: ["ng", "n"],
    anchorWord: "ring",
    anchorImage: "💍",
    category: "consonant",
    subcategory: "nasal",
    unlocked: false,
  },
  // FRICATIVES
  {
    phoneme: "/s/",
    graphemes: ["s", "ss", "c", "ce", "se"],
    anchorWord: "sun",
    anchorImage: "☀️",
    category: "consonant",
    subcategory: "fricative",
    unlocked: false,
  },
  {
    phoneme: "/z/",
    graphemes: ["z", "zz", "s", "se"],
    anchorWord: "zebra",
    anchorImage: "🦓",
    category: "consonant",
    subcategory: "fricative",
    unlocked: false,
  },
  {
    phoneme: "/th/",
    graphemes: ["th"],
    anchorWord: "thumb",
    anchorImage: "👍",
    category: "consonant",
    subcategory: "fricative",
    unlocked: false,
  },
  {
    phoneme: "/th/",
    graphemes: ["th"],
    anchorWord: "this",
    anchorImage: "👈",
    category: "consonant",
    subcategory: "fricative",
    unlocked: false,
  },
  {
    phoneme: "/sh/",
    graphemes: ["sh", "ch", "ti", "ci", "s", "ss"],
    anchorWord: "ship",
    anchorImage: "🚢",
    category: "consonant",
    subcategory: "fricative",
    unlocked: false,
  },
  {
    phoneme: "/zh/",
    graphemes: ["s", "ge"],
    anchorWord: "treasure",
    anchorImage: "💎",
    category: "consonant",
    subcategory: "fricative",
    unlocked: false,
  },
  {
    phoneme: "/f/",
    graphemes: ["f", "ff", "ph", "gh"],
    anchorWord: "fish",
    anchorImage: "🐟",
    category: "consonant",
    subcategory: "fricative",
    unlocked: false,
  },
  {
    phoneme: "/v/",
    graphemes: ["v", "ve"],
    anchorWord: "van",
    anchorImage: "🚐",
    category: "consonant",
    subcategory: "fricative",
    unlocked: false,
  },
  {
    phoneme: "/h/",
    graphemes: ["h", "wh"],
    anchorWord: "hat",
    anchorImage: "🎩",
    category: "consonant",
    subcategory: "fricative",
    unlocked: false,
  },
  // GLIDES
  {
    phoneme: "/y/",
    graphemes: ["y"],
    anchorWord: "yarn",
    anchorImage: "🧶",
    category: "consonant",
    subcategory: "glide",
    unlocked: false,
  },
  {
    phoneme: "/wh/",
    graphemes: ["wh"],
    anchorWord: "whale",
    anchorImage: "🐋",
    category: "consonant",
    subcategory: "glide",
    unlocked: false,
  },
  {
    phoneme: "/w/",
    graphemes: ["w"],
    anchorWord: "wagon",
    anchorImage: "🛒",
    category: "consonant",
    subcategory: "glide",
    unlocked: false,
  },
  // LIQUIDS
  {
    phoneme: "/r/",
    graphemes: ["r", "rr", "wr", "rh"],
    anchorWord: "rainbow",
    anchorImage: "🌈",
    category: "consonant",
    subcategory: "liquid",
    unlocked: false,
  },
  {
    phoneme: "/l/",
    graphemes: ["l", "ll"],
    anchorWord: "lion",
    anchorImage: "🦁",
    category: "consonant",
    subcategory: "liquid",
    unlocked: false,
  },
  // TWO SOUNDS
  {
    phoneme: "/x/",
    graphemes: ["x"],
    anchorWord: "fox",
    anchorImage: "🦊",
    category: "consonant",
    subcategory: "two_sounds",
    unlocked: false,
  },
  {
    phoneme: "/qu/",
    graphemes: ["qu"],
    anchorWord: "queen",
    anchorImage: "👸",
    category: "consonant",
    subcategory: "two_sounds",
    unlocked: false,
  },
];

// Combine all phase lessons
export const SAMPLE_LESSONS: Lesson[] = [
  ...phase1Lessons,
  ...phase2Lessons,
  ...phase3Lessons,
  ...phase4Lessons,
];
