import { PhaseInfo, Lesson, PhonemeCard } from "@/types/curriculum";

export const PHASES: PhaseInfo[] = [
  {
    phase: 1,
    title: "Pre-Reading Skills",
    description: "Phonological & Phonemic Awareness",
    lessonRange: [1, 5],
    color: "#FF6B9D",
  },
  {
    phase: 2,
    title: "The Alphabetic Principle",
    description: "Letter-Sounds & CVC Words",
    lessonRange: [6, 25],
    color: "#4ECDC4",
  },
  {
    phase: 3,
    title: "Expanding the Code",
    description: "Digraphs, Blends & Patterns",
    lessonRange: [26, 45],
    color: "#FFD93D",
  },
  {
    phase: 4,
    title: "Advanced Decoding",
    description: "VCe, Syllables & Morphology",
    lessonRange: [46, 55],
    color: "#A78BFA",
  },
];

export const INITIAL_PHONEME_CARDS: PhonemeCard[] = [
  {
    phoneme: "/m/",
    graphemes: ["m"],
    anchorWord: "moon",
    anchorImage: "🌙",
    category: "consonant",
    subcategory: "nasal",
    unlocked: false,
  },
  {
    phoneme: "/s/",
    graphemes: ["s"],
    anchorWord: "sun",
    anchorImage: "☀️",
    category: "consonant",
    subcategory: "fricative",
    unlocked: false,
  },
  {
    phoneme: "/p/",
    graphemes: ["p"],
    anchorWord: "pig",
    anchorImage: "🐷",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/ă/",
    graphemes: ["a"],
    anchorWord: "apple",
    anchorImage: "🍎",
    category: "vowel",
    unlocked: false,
  },
  {
    phoneme: "/t/",
    graphemes: ["t"],
    anchorWord: "tiger",
    anchorImage: "🐯",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/ĭ/",
    graphemes: ["i"],
    anchorWord: "igloo",
    anchorImage: "🏔️",
    category: "vowel",
    unlocked: false,
  },
  {
    phoneme: "/n/",
    graphemes: ["n"],
    anchorWord: "nest",
    anchorImage: "🪺",
    category: "consonant",
    subcategory: "nasal",
    unlocked: false,
  },
  {
    phoneme: "/k/",
    graphemes: ["c", "k"],
    anchorWord: "cat",
    anchorImage: "🐱",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/h/",
    graphemes: ["h"],
    anchorWord: "hat",
    anchorImage: "🎩",
    category: "consonant",
    subcategory: "fricative",
    unlocked: false,
  },
  {
    phoneme: "/d/",
    graphemes: ["d"],
    anchorWord: "dog",
    anchorImage: "🐕",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/ŏ/",
    graphemes: ["o"],
    anchorWord: "octopus",
    anchorImage: "🐙",
    category: "vowel",
    unlocked: false,
  },
  {
    phoneme: "/g/",
    graphemes: ["g"],
    anchorWord: "goat",
    anchorImage: "🐐",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/f/",
    graphemes: ["f"],
    anchorWord: "fish",
    anchorImage: "🐟",
    category: "consonant",
    subcategory: "fricative",
    unlocked: false,
  },
  {
    phoneme: "/b/",
    graphemes: ["b"],
    anchorWord: "ball",
    anchorImage: "⚽",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/ŭ/",
    graphemes: ["u"],
    anchorWord: "umbrella",
    anchorImage: "☂️",
    category: "vowel",
    unlocked: false,
  },
  {
    phoneme: "/l/",
    graphemes: ["l"],
    anchorWord: "lion",
    anchorImage: "🦁",
    category: "consonant",
    subcategory: "liquid",
    unlocked: false,
  },
  {
    phoneme: "/ĕ/",
    graphemes: ["e"],
    anchorWord: "egg",
    anchorImage: "🥚",
    category: "vowel",
    unlocked: false,
  },
];

export const SAMPLE_LESSONS: Lesson[] = [
  {
    lesson_number: 1,
    phase: 1,
    title: "Rhyme Time",
    description: "Learn to recognize and create rhyming words",
    exercises: [
      {
        exercise_id: "L1-RhymeMatch-001",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "cat", image: "🐱" },
          choices: [
            { word: "hat", image: "🎩", isCorrect: true },
            { word: "dog", image: "🐕", isCorrect: false },
            { word: "car", image: "🚗", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["cat.mp3", "hat.mp3", "dog.mp3", "car.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-002",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "bug", image: "🐛" },
          choices: [
            { word: "rug", image: "🧶", isCorrect: true },
            { word: "sun", image: "☀️", isCorrect: false },
            { word: "tree", image: "🌳", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["bug.mp3", "rug.mp3", "sun.mp3", "tree.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-003",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "pin", image: "📌" },
          choices: [
            { word: "fin", image: "🐟", isCorrect: true },
            { word: "cup", image: "☕", isCorrect: false },
            { word: "ball", image: "⚽", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["pin.mp3", "fin.mp3", "cup.mp3", "ball.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-004",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "log", image: "🪵" },
          choices: [
            { word: "dog", image: "🐕", isCorrect: true },
            { word: "cat", image: "🐱", isCorrect: false },
            { word: "fish", image: "🐟", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["log.mp3", "dog.mp3", "cat.mp3", "fish.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-005",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "sun", image: "☀️" },
          choices: [
            { word: "run", image: "🏃", isCorrect: true },
            { word: "moon", image: "🌙", isCorrect: false },
            { word: "star", image: "⭐", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["sun.mp3", "run.mp3", "moon.mp3", "star.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-006",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "man", image: "👨" },
          choices: [
            { word: "pan", image: "🍳", isCorrect: true },
            { word: "dog", image: "🐕", isCorrect: false },
            { word: "cup", image: "☕", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["man.mp3", "pan.mp3", "dog.mp3", "cup.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-007",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "bed", image: "🛏️" },
          choices: [
            { word: "red", image: "🔴", isCorrect: true },
            { word: "blue", image: "🔵", isCorrect: false },
            { word: "green", image: "🟢", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["bed.mp3", "red.mp3", "blue.mp3", "green.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-008",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "pig", image: "🐷" },
          choices: [
            { word: "wig", image: "💇", isCorrect: true },
            { word: "cow", image: "🐄", isCorrect: false },
            { word: "hen", image: "🐔", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["pig.mp3", "wig.mp3", "cow.mp3", "hen.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-009",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "hop", image: "🦘" },
          choices: [
            { word: "mop", image: "🧹", isCorrect: true },
            { word: "run", image: "🏃", isCorrect: false },
            { word: "sit", image: "🪑", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["hop.mp3", "mop.mp3", "run.mp3", "sit.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-010",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "jet", image: "✈️" },
          choices: [
            { word: "net", image: "🥅", isCorrect: true },
            { word: "car", image: "🚗", isCorrect: false },
            { word: "boat", image: "⛵", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["jet.mp3", "net.mp3", "car.mp3", "boat.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
    ],
  },
  {
    lesson_number: 2,
    phase: 1,
    title: "Counting Words",
    description: "Learn that sentences are made of individual words",
    exercises: [
      {
        exercise_id: "L2-WordTapper-001",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "Dogs run.",
          wordCount: 2,
        },
        response_type: "tap_count",
        assets: { audio: ["dogs_run.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-002",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "Cats play.",
          wordCount: 2,
        },
        response_type: "tap_count",
        assets: { audio: ["cats_play.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-003",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "Birds fly.",
          wordCount: 2,
        },
        response_type: "tap_count",
        assets: { audio: ["birds_fly.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-004",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "The dog ran.",
          wordCount: 3,
        },
        response_type: "tap_count",
        assets: { audio: ["the_dog_ran.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-005",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "A cat sat.",
          wordCount: 3,
        },
        response_type: "tap_count",
        assets: { audio: ["a_cat_sat.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-006",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "Big birds sing.",
          wordCount: 3,
        },
        response_type: "tap_count",
        assets: { audio: ["big_birds_sing.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-007",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "The dog ran fast.",
          wordCount: 4,
        },
        response_type: "tap_count",
        assets: { audio: ["the_dog_ran_fast.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-008",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "A little cat sat.",
          wordCount: 4,
        },
        response_type: "tap_count",
        assets: { audio: ["a_little_cat_sat.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-009",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "The big birds sing.",
          wordCount: 4,
        },
        response_type: "tap_count",
        assets: { audio: ["the_big_birds_sing.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
    ],
  },
  {
    lesson_number: 6,
    phase: 2,
    title: "First Letters: m, s, p, a",
    description: "Learn your first letter sounds and build words!",
    new_graphemes: ["m", "s", "p", "a"],
    new_irregular_words: ["the", "a"],
    exercises: [
      {
        exercise_id: "L6-WordBuilder-001",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "map",
          letters: ["m", "a", "p"],
          image: "🗺️",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["m.mp3", "a.mp3", "p.mp3", "map.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L6-WordBuilder-002",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "Sam",
          letters: ["S", "a", "m"],
        },
        response_type: "drag_and_drop",
        assets: { audio: ["s.mp3", "a.mp3", "m.mp3", "sam.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
    ],
    story: {
      title: "Sam, a cat",
      text: "Sam sat. Sam and Nan sat. Nan can pat Sam.",
    },
  },
];
