import { PhaseInfo, Lesson, PhonemeCard } from "@/types/curriculum";

export const PHASES: PhaseInfo[] = [
  {
    phase: 1,
    title: "Pre-Reading Skills",
    description: "Phonological & Phonemic Awareness",
    lessonRange: [1, 5],
    color: "#FF6B9D",
  },
  {
    phase: 2,
    title: "The Alphabetic Principle",
    description: "Letter-Sounds & CVC Words",
    lessonRange: [6, 25],
    color: "#4ECDC4",
  },
  {
    phase: 3,
    title: "Expanding the Code",
    description: "Digraphs, Blends & Patterns",
    lessonRange: [26, 45],
    color: "#FFD93D",
  },
  {
    phase: 4,
    title: "Advanced Decoding",
    description: "VCe, Syllables & Morphology",
    lessonRange: [46, 55],
    color: "#A78BFA",
  },
];

export const INITIAL_PHONEME_CARDS: PhonemeCard[] = [
  {
    phoneme: "/m/",
    graphemes: ["m"],
    anchorWord: "moon",
    anchorImage: "🌙",
    category: "consonant",
    subcategory: "nasal",
    unlocked: false,
  },
  {
    phoneme: "/s/",
    graphemes: ["s"],
    anchorWord: "sun",
    anchorImage: "☀️",
    category: "consonant",
    subcategory: "fricative",
    unlocked: false,
  },
  {
    phoneme: "/p/",
    graphemes: ["p"],
    anchorWord: "pig",
    anchorImage: "🐷",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/ă/",
    graphemes: ["a"],
    anchorWord: "apple",
    anchorImage: "🍎",
    category: "vowel",
    unlocked: false,
  },
  {
    phoneme: "/t/",
    graphemes: ["t"],
    anchorWord: "tiger",
    anchorImage: "🐯",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/ĭ/",
    graphemes: ["i"],
    anchorWord: "igloo",
    anchorImage: "🏔️",
    category: "vowel",
    unlocked: false,
  },
  {
    phoneme: "/n/",
    graphemes: ["n"],
    anchorWord: "nest",
    anchorImage: "🪺",
    category: "consonant",
    subcategory: "nasal",
    unlocked: false,
  },
  {
    phoneme: "/k/",
    graphemes: ["c", "k"],
    anchorWord: "cat",
    anchorImage: "🐱",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/h/",
    graphemes: ["h"],
    anchorWord: "hat",
    anchorImage: "🎩",
    category: "consonant",
    subcategory: "fricative",
    unlocked: false,
  },
  {
    phoneme: "/d/",
    graphemes: ["d"],
    anchorWord: "dog",
    anchorImage: "🐕",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/ŏ/",
    graphemes: ["o"],
    anchorWord: "octopus",
    anchorImage: "🐙",
    category: "vowel",
    unlocked: false,
  },
  {
    phoneme: "/g/",
    graphemes: ["g"],
    anchorWord: "goat",
    anchorImage: "🐐",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/f/",
    graphemes: ["f"],
    anchorWord: "fish",
    anchorImage: "🐟",
    category: "consonant",
    subcategory: "fricative",
    unlocked: false,
  },
  {
    phoneme: "/b/",
    graphemes: ["b"],
    anchorWord: "ball",
    anchorImage: "⚽",
    category: "consonant",
    subcategory: "stop",
    unlocked: false,
  },
  {
    phoneme: "/ŭ/",
    graphemes: ["u"],
    anchorWord: "umbrella",
    anchorImage: "☂️",
    category: "vowel",
    unlocked: false,
  },
  {
    phoneme: "/l/",
    graphemes: ["l"],
    anchorWord: "lion",
    anchorImage: "🦁",
    category: "consonant",
    subcategory: "liquid",
    unlocked: false,
  },
  {
    phoneme: "/ĕ/",
    graphemes: ["e"],
    anchorWord: "egg",
    anchorImage: "🥚",
    category: "vowel",
    unlocked: false,
  },
];

export const SAMPLE_LESSONS: Lesson[] = [
  {
    lesson_number: 1,
    phase: 1,
    title: "Rhyme Time",
    description: "Learn to recognize and create rhyming words",
    exercises: [
      {
        exercise_id: "L1-RhymeMatch-001",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "cat", image: "🐱" },
          choices: [
            { word: "hat", image: "🎩", isCorrect: true },
            { word: "dog", image: "🐕", isCorrect: false },
            { word: "car", image: "🚗", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["cat.mp3", "hat.mp3", "dog.mp3", "car.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-002",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "bug", image: "🐛" },
          choices: [
            { word: "rug", image: "🧶", isCorrect: true },
            { word: "sun", image: "☀️", isCorrect: false },
            { word: "tree", image: "🌳", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["bug.mp3", "rug.mp3", "sun.mp3", "tree.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-003",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "pin", image: "📌" },
          choices: [
            { word: "fin", image: "🐟", isCorrect: true },
            { word: "cup", image: "☕", isCorrect: false },
            { word: "ball", image: "⚽", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["pin.mp3", "fin.mp3", "cup.mp3", "ball.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-004",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "log", image: "🪵" },
          choices: [
            { word: "dog", image: "🐕", isCorrect: true },
            { word: "cat", image: "🐱", isCorrect: false },
            { word: "fish", image: "🐟", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["log.mp3", "dog.mp3", "cat.mp3", "fish.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-005",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "sun", image: "☀️" },
          choices: [
            { word: "run", image: "🏃", isCorrect: true },
            { word: "moon", image: "🌙", isCorrect: false },
            { word: "star", image: "⭐", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["sun.mp3", "run.mp3", "moon.mp3", "star.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-006",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "man", image: "👨" },
          choices: [
            { word: "pan", image: "🍳", isCorrect: true },
            { word: "dog", image: "🐕", isCorrect: false },
            { word: "cup", image: "☕", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["man.mp3", "pan.mp3", "dog.mp3", "cup.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-007",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "bed", image: "🛏️" },
          choices: [
            { word: "red", image: "🔴", isCorrect: true },
            { word: "blue", image: "🔵", isCorrect: false },
            { word: "green", image: "🟢", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["bed.mp3", "red.mp3", "blue.mp3", "green.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-008",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "pig", image: "🐷" },
          choices: [
            { word: "wig", image: "💇", isCorrect: true },
            { word: "cow", image: "🐄", isCorrect: false },
            { word: "hen", image: "🐔", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["pig.mp3", "wig.mp3", "cow.mp3", "hen.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-009",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "hop", image: "🦘" },
          choices: [
            { word: "mop", image: "🧹", isCorrect: true },
            { word: "run", image: "🏃", isCorrect: false },
            { word: "sit", image: "🪑", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["hop.mp3", "mop.mp3", "run.mp3", "sit.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L1-RhymeMatch-010",
        lesson_number: 1,
        exercise_type: "Rhyme Match",
        skill_focus: "Rhyme Recognition",
        data: {
          target: { word: "jet", image: "✈️" },
          choices: [
            { word: "net", image: "🥅", isCorrect: true },
            { word: "car", image: "🚗", isCorrect: false },
            { word: "boat", image: "⛵", isCorrect: false },
          ],
        },
        response_type: "tap_image",
        assets: { audio: ["jet.mp3", "net.mp3", "car.mp3", "boat.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
    ],
  },
  {
    lesson_number: 2,
    phase: 1,
    title: "Counting Words",
    description: "Learn that sentences are made of individual words",
    exercises: [
      {
        exercise_id: "L2-WordTapper-001",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "Dogs run.",
          wordCount: 2,
        },
        response_type: "tap_count",
        assets: { audio: ["dogs_run.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-002",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "Cats play.",
          wordCount: 2,
        },
        response_type: "tap_count",
        assets: { audio: ["cats_play.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-003",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "Birds fly.",
          wordCount: 2,
        },
        response_type: "tap_count",
        assets: { audio: ["birds_fly.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-004",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "The dog ran.",
          wordCount: 3,
        },
        response_type: "tap_count",
        assets: { audio: ["the_dog_ran.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-005",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "A cat sat.",
          wordCount: 3,
        },
        response_type: "tap_count",
        assets: { audio: ["a_cat_sat.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-006",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "Big birds sing.",
          wordCount: 3,
        },
        response_type: "tap_count",
        assets: { audio: ["big_birds_sing.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-007",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "The dog ran fast.",
          wordCount: 4,
        },
        response_type: "tap_count",
        assets: { audio: ["the_dog_ran_fast.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-008",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "A little cat sat.",
          wordCount: 4,
        },
        response_type: "tap_count",
        assets: { audio: ["a_little_cat_sat.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L2-WordTapper-009",
        lesson_number: 2,
        exercise_type: "Word Tapper",
        skill_focus: "Sentence Segmentation",
        data: {
          sentence: "The big birds sing.",
          wordCount: 4,
        },
        response_type: "tap_count",
        assets: { audio: ["the_big_birds_sing.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
    ],
  },
  {
    lesson_number: 3,
    phase: 1,
    title: "Syllable Fun",
    description: "Learn to blend and segment syllables in words",
    exercises: [
      {
        exercise_id: "L3-SyllableSquish-001",
        lesson_number: 3,
        exercise_type: "Syllable Squish",
        skill_focus: "Syllable Segmentation",
        data: {
          word: "tiger",
          image: "🐯",
          syllableCount: 2,
        },
        response_type: "tap_count",
        assets: { audio: ["tiger.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L3-SyllableSquish-002",
        lesson_number: 3,
        exercise_type: "Syllable Squish",
        skill_focus: "Syllable Segmentation",
        data: {
          word: "puppy",
          image: "🐶",
          syllableCount: 2,
        },
        response_type: "tap_count",
        assets: { audio: ["puppy.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L3-SyllableSquish-003",
        lesson_number: 3,
        exercise_type: "Syllable Squish",
        skill_focus: "Syllable Segmentation",
        data: {
          word: "apple",
          image: "🍎",
          syllableCount: 2,
        },
        response_type: "tap_count",
        assets: { audio: ["apple.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L3-SyllableSquish-004",
        lesson_number: 3,
        exercise_type: "Syllable Squish",
        skill_focus: "Syllable Segmentation",
        data: {
          word: "bubble",
          image: "🫧",
          syllableCount: 2,
        },
        response_type: "tap_count",
        assets: { audio: ["bubble.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L3-SyllableSquish-005",
        lesson_number: 3,
        exercise_type: "Syllable Squish",
        skill_focus: "Syllable Segmentation",
        data: {
          word: "happy",
          image: "😊",
          syllableCount: 2,
        },
        response_type: "tap_count",
        assets: { audio: ["happy.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L3-SyllableSquish-006",
        lesson_number: 3,
        exercise_type: "Syllable Squish",
        skill_focus: "Syllable Segmentation",
        data: {
          word: "little",
          image: "🐭",
          syllableCount: 2,
        },
        response_type: "tap_count",
        assets: { audio: ["little.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L3-SyllableSquish-007",
        lesson_number: 3,
        exercise_type: "Syllable Squish",
        skill_focus: "Syllable Segmentation",
        data: {
          word: "butterfly",
          image: "🦋",
          syllableCount: 3,
        },
        response_type: "tap_count",
        assets: { audio: ["butterfly.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L3-SyllableSquish-008",
        lesson_number: 3,
        exercise_type: "Syllable Squish",
        skill_focus: "Syllable Segmentation",
        data: {
          word: "elephant",
          image: "🐘",
          syllableCount: 3,
        },
        response_type: "tap_count",
        assets: { audio: ["elephant.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L3-SyllableSquish-009",
        lesson_number: 3,
        exercise_type: "Syllable Squish",
        skill_focus: "Syllable Segmentation",
        data: {
          word: "banana",
          image: "🍌",
          syllableCount: 3,
        },
        response_type: "tap_count",
        assets: { audio: ["banana.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L3-SyllableSquish-010",
        lesson_number: 3,
        exercise_type: "Syllable Squish",
        skill_focus: "Syllable Segmentation",
        data: {
          word: "computer",
          image: "💻",
          syllableCount: 3,
        },
        response_type: "tap_count",
        assets: { audio: ["computer.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L3-SyllableSquish-011",
        lesson_number: 3,
        exercise_type: "Syllable Squish",
        skill_focus: "Syllable Segmentation",
        data: {
          word: "umbrella",
          image: "☂️",
          syllableCount: 3,
        },
        response_type: "tap_count",
        assets: { audio: ["umbrella.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L3-SyllableSquish-012",
        lesson_number: 3,
        exercise_type: "Syllable Squish",
        skill_focus: "Syllable Segmentation",
        data: {
          word: "caterpillar",
          image: "🐛",
          syllableCount: 4,
        },
        response_type: "tap_count",
        assets: { audio: ["caterpillar.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L3-SyllableSquish-013",
        lesson_number: 3,
        exercise_type: "Syllable Squish",
        skill_focus: "Syllable Segmentation",
        data: {
          word: "helicopter",
          image: "🚁",
          syllableCount: 4,
        },
        response_type: "tap_count",
        assets: { audio: ["helicopter.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L3-SyllableSquish-014",
        lesson_number: 3,
        exercise_type: "Syllable Squish",
        skill_focus: "Syllable Segmentation",
        data: {
          word: "watermelon",
          image: "🍉",
          syllableCount: 4,
        },
        response_type: "tap_count",
        assets: { audio: ["watermelon.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L3-SyllableSquish-015",
        lesson_number: 3,
        exercise_type: "Syllable Squish",
        skill_focus: "Syllable Segmentation",
        data: {
          word: "television",
          image: "📺",
          syllableCount: 4,
        },
        response_type: "tap_count",
        assets: { audio: ["television.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
    ],
  },
  {
    lesson_number: 4,
    phase: 1,
    title: "Sound Slide",
    description: "Learn to blend onset and rime sounds together",
    exercises: [
      {
        exercise_id: "L4-SoundSlide-001",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "c",
          rime: "at",
          word: "cat",
          image: "🐱",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["c.mp3", "at.mp3", "cat.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-002",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "b",
          rime: "at",
          word: "bat",
          image: "🦇",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["b.mp3", "at.mp3", "bat.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-003",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "s",
          rime: "at",
          word: "sat",
          image: "🪑",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["s.mp3", "at.mp3", "sat.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-004",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "m",
          rime: "at",
          word: "mat",
          image: "🧘",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["m.mp3", "at.mp3", "mat.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-005",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "h",
          rime: "at",
          word: "hat",
          image: "🎩",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["h.mp3", "at.mp3", "hat.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-006",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "p",
          rime: "in",
          word: "pin",
          image: "📌",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["p.mp3", "in.mp3", "pin.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-007",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "f",
          rime: "in",
          word: "fin",
          image: "🐟",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["f.mp3", "in.mp3", "fin.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-008",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "b",
          rime: "in",
          word: "bin",
          image: "🗑️",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["b.mp3", "in.mp3", "bin.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-009",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "w",
          rime: "in",
          word: "win",
          image: "🏆",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["w.mp3", "in.mp3", "win.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-010",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "t",
          rime: "op",
          word: "top",
          image: "🔝",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["t.mp3", "op.mp3", "top.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-011",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "m",
          rime: "op",
          word: "mop",
          image: "🧹",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["m.mp3", "op.mp3", "mop.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-012",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "h",
          rime: "op",
          word: "hop",
          image: "🦘",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["h.mp3", "op.mp3", "hop.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-013",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "p",
          rime: "op",
          word: "pop",
          image: "🎈",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["p.mp3", "op.mp3", "pop.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-014",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "b",
          rime: "ug",
          word: "bug",
          image: "🐛",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["b.mp3", "ug.mp3", "bug.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-015",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "r",
          rime: "ug",
          word: "rug",
          image: "🧶",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["r.mp3", "ug.mp3", "rug.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-016",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "h",
          rime: "ug",
          word: "hug",
          image: "🤗",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["h.mp3", "ug.mp3", "hug.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L4-SoundSlide-017",
        lesson_number: 4,
        exercise_type: "Sound Slide",
        skill_focus: "Onset-Rime Blending",
        data: {
          onset: "m",
          rime: "ug",
          word: "mug",
          image: "☕",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["m.mp3", "ug.mp3", "mug.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
    ],
  },
  {
    lesson_number: 5,
    phase: 1,
    title: "Sound Detective",
    description: "Find the first, last, and middle sounds in words",
    exercises: [
      {
        exercise_id: "L5-SoundDetective-001",
        lesson_number: 5,
        exercise_type: "Sound Detective",
        skill_focus: "Phoneme Isolation (First Sound)",
        data: {
          word: "sun",
          image: "☀️",
          targetPosition: "first",
          correctSound: "s",
          choices: ["s", "m", "t"],
        },
        response_type: "tap_choice",
        assets: { audio: ["sun.mp3", "s.mp3", "m.mp3", "t.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L5-SoundDetective-002",
        lesson_number: 5,
        exercise_type: "Sound Detective",
        skill_focus: "Phoneme Isolation (Last Sound)",
        data: {
          word: "sun",
          image: "☀️",
          targetPosition: "last",
          correctSound: "n",
          choices: ["n", "s", "p"],
        },
        response_type: "tap_choice",
        assets: { audio: ["sun.mp3", "n.mp3", "s.mp3", "p.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L5-SoundDetective-003",
        lesson_number: 5,
        exercise_type: "Sound Detective",
        skill_focus: "Phoneme Isolation (Middle Sound)",
        data: {
          word: "sun",
          image: "☀️",
          targetPosition: "middle",
          correctSound: "u",
          choices: ["u", "a", "i"],
        },
        response_type: "tap_choice",
        assets: { audio: ["sun.mp3", "u.mp3", "a.mp3", "i.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L5-SoundDetective-004",
        lesson_number: 5,
        exercise_type: "Sound Detective",
        skill_focus: "Phoneme Isolation (First Sound)",
        data: {
          word: "map",
          image: "🗺️",
          targetPosition: "first",
          correctSound: "m",
          choices: ["m", "p", "b"],
        },
        response_type: "tap_choice",
        assets: { audio: ["map.mp3", "m.mp3", "p.mp3", "b.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L5-SoundDetective-005",
        lesson_number: 5,
        exercise_type: "Sound Detective",
        skill_focus: "Phoneme Isolation (Last Sound)",
        data: {
          word: "map",
          image: "🗺️",
          targetPosition: "last",
          correctSound: "p",
          choices: ["p", "t", "d"],
        },
        response_type: "tap_choice",
        assets: { audio: ["map.mp3", "p.mp3", "t.mp3", "d.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L5-SoundDetective-006",
        lesson_number: 5,
        exercise_type: "Sound Detective",
        skill_focus: "Phoneme Isolation (Middle Sound)",
        data: {
          word: "map",
          image: "🗺️",
          targetPosition: "middle",
          correctSound: "a",
          choices: ["a", "e", "o"],
        },
        response_type: "tap_choice",
        assets: { audio: ["map.mp3", "a.mp3", "e.mp3", "o.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L5-SoundDetective-007",
        lesson_number: 5,
        exercise_type: "Sound Detective",
        skill_focus: "Phoneme Isolation (First Sound)",
        data: {
          word: "pig",
          image: "🐷",
          targetPosition: "first",
          correctSound: "p",
          choices: ["p", "b", "d"],
        },
        response_type: "tap_choice",
        assets: { audio: ["pig.mp3", "p.mp3", "b.mp3", "d.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L5-SoundDetective-008",
        lesson_number: 5,
        exercise_type: "Sound Detective",
        skill_focus: "Phoneme Isolation (Last Sound)",
        data: {
          word: "pig",
          image: "🐷",
          targetPosition: "last",
          correctSound: "g",
          choices: ["g", "k", "d"],
        },
        response_type: "tap_choice",
        assets: { audio: ["pig.mp3", "g.mp3", "k.mp3", "d.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L5-SoundDetective-009",
        lesson_number: 5,
        exercise_type: "Sound Detective",
        skill_focus: "Phoneme Isolation (Middle Sound)",
        data: {
          word: "pig",
          image: "🐷",
          targetPosition: "middle",
          correctSound: "i",
          choices: ["i", "e", "a"],
        },
        response_type: "tap_choice",
        assets: { audio: ["pig.mp3", "i.mp3", "e.mp3", "a.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L5-SoundDetective-010",
        lesson_number: 5,
        exercise_type: "Sound Detective",
        skill_focus: "Phoneme Isolation (First Sound)",
        data: {
          word: "top",
          image: "🔝",
          targetPosition: "first",
          correctSound: "t",
          choices: ["t", "d", "p"],
        },
        response_type: "tap_choice",
        assets: { audio: ["top.mp3", "t.mp3", "d.mp3", "p.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L5-SoundDetective-011",
        lesson_number: 5,
        exercise_type: "Sound Detective",
        skill_focus: "Phoneme Isolation (Last Sound)",
        data: {
          word: "top",
          image: "🔝",
          targetPosition: "last",
          correctSound: "p",
          choices: ["p", "b", "t"],
        },
        response_type: "tap_choice",
        assets: { audio: ["top.mp3", "p.mp3", "b.mp3", "t.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L5-SoundDetective-012",
        lesson_number: 5,
        exercise_type: "Sound Detective",
        skill_focus: "Phoneme Isolation (Middle Sound)",
        data: {
          word: "top",
          image: "🔝",
          targetPosition: "middle",
          correctSound: "o",
          choices: ["o", "a", "u"],
        },
        response_type: "tap_choice",
        assets: { audio: ["top.mp3", "o.mp3", "a.mp3", "u.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L5-SoundDetective-013",
        lesson_number: 5,
        exercise_type: "Sound Detective",
        skill_focus: "Phoneme Isolation (First Sound)",
        data: {
          word: "bug",
          image: "🐛",
          targetPosition: "first",
          correctSound: "b",
          choices: ["b", "d", "p"],
        },
        response_type: "tap_choice",
        assets: { audio: ["bug.mp3", "b.mp3", "d.mp3", "p.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L5-SoundDetective-014",
        lesson_number: 5,
        exercise_type: "Sound Detective",
        skill_focus: "Phoneme Isolation (Last Sound)",
        data: {
          word: "bug",
          image: "🐛",
          targetPosition: "last",
          correctSound: "g",
          choices: ["g", "k", "d"],
        },
        response_type: "tap_choice",
        assets: { audio: ["bug.mp3", "g.mp3", "k.mp3", "d.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L5-SoundDetective-015",
        lesson_number: 5,
        exercise_type: "Sound Detective",
        skill_focus: "Phoneme Isolation (Middle Sound)",
        data: {
          word: "bug",
          image: "🐛",
          targetPosition: "middle",
          correctSound: "u",
          choices: ["u", "o", "i"],
        },
        response_type: "tap_choice",
        assets: { audio: ["bug.mp3", "u.mp3", "o.mp3", "i.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
    ],
  },
  {
    lesson_number: 6,
    phase: 2,
    title: "First Letters: m, s, p, a",
    description: "Learn your first letter sounds and build words!",
    new_graphemes: ["m", "s", "p", "a"],
    new_irregular_words: ["the", "a"],
    exercises: [
      {
        exercise_id: "L6-WordBuilder-001",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "map",
          letters: ["m", "a", "p"],
          image: "🗺️",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["m.mp3", "a.mp3", "p.mp3", "map.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L6-WordBuilder-002",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "Sam",
          letters: ["S", "a", "m"],
        },
        response_type: "drag_and_drop",
        assets: { audio: ["s.mp3", "a.mp3", "m.mp3", "sam.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
    ],
    story: {
      title: "Sam, a cat",
      text: "Sam sat. Sam and Nan sat. Nan can pat Sam.",
    },
  },
];
