import { Lesson } from "@/types/curriculum";

export const phase2Lessons: Lesson[] = [
  {
    lesson_number: 6,
    phase: 2,
    title: "First Letters: m, s, p, a",
    description: "Learn your first letter sounds and build words!",
    new_graphemes: ["m", "s", "p", "a"],
    new_irregular_words: ["the", "a"],
    exercises: [
      {
        exercise_id: "L6-WordBuilder-001",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "map",
          letters: ["m", "a", "p"],
          image: "🗺️",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["m.mp3", "a.mp3", "p.mp3", "map.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L6-WordBuilder-002",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "Sam",
          letters: ["S", "a", "m"],
          image: "👦",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["s.mp3", "a.mp3", "m.mp3", "sam.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L6-WordBuilder-003",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "am",
          letters: ["a", "m"],
          image: "✋",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["a.mp3", "m.mp3", "am.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L6-WordBuilder-004",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "Pam",
          letters: ["P", "a", "m"],
          image: "👧",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["p.mp3", "a.mp3", "m.mp3", "pam.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L6-WordBuilder-005",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "sap",
          letters: ["s", "a", "p"],
          image: "🌳",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["s.mp3", "a.mp3", "p.mp3", "sap.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L6-WordBuilder-006",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "at",
          letters: ["a", "t"],
          image: "📍",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["a.mp3", "t.mp3", "at.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L6-WordBuilder-007",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "pat",
          letters: ["p", "a", "t"],
          image: "✋",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["p.mp3", "a.mp3", "t.mp3", "pat.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L6-WordBuilder-008",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "sat",
          letters: ["s", "a", "t"],
          image: "🪑",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["s.mp3", "a.mp3", "t.mp3", "sat.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L6-WordBuilder-009",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "tap",
          letters: ["t", "a", "p"],
          image: "👆",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["t.mp3", "a.mp3", "p.mp3", "tap.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L6-WordBuilder-010",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "mat",
          letters: ["m", "a", "t"],
          image: "🧘",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["m.mp3", "a.mp3", "t.mp3", "mat.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L6-WordBuilder-011",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "sap",
          letters: ["s", "a", "p"],
          image: "🌳",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["s.mp3", "a.mp3", "p.mp3", "sap.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L6-WordBuilder-012",
        lesson_number: 6,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "as",
          letters: ["a", "s"],
          image: "➡️",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["a.mp3", "s.mp3", "as.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
    ],
    story: {
      title: "Sam, a cat",
      text: "Sam sat. Sam and Nan sat. Nan can pat Sam.",
    },
  },
  {
    lesson_number: 7,
    phase: 2,
    title: "New Letters: t, i, n",
    description: "Learn more letter sounds and build new words!",
    new_graphemes: ["t", "i", "n"],
    new_irregular_words: ["I", "to"],
    exercises: [
      {
        exercise_id: "L7-WordBuilder-001",
        lesson_number: 7,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "tin",
          letters: ["t", "i", "n"],
          image: "🥫",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["t.mp3", "i.mp3", "n.mp3", "tin.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L7-WordBuilder-002",
        lesson_number: 7,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "sit",
          letters: ["s", "i", "t"],
          image: "🪑",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["s.mp3", "i.mp3", "t.mp3", "sit.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L7-WordBuilder-003",
        lesson_number: 7,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "pin",
          letters: ["p", "i", "n"],
          image: "📌",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["p.mp3", "i.mp3", "n.mp3", "pin.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L7-WordBuilder-004",
        lesson_number: 7,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "nap",
          letters: ["n", "a", "p"],
          image: "😴",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["n.mp3", "a.mp3", "p.mp3", "nap.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L7-WordBuilder-005",
        lesson_number: 7,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "tan",
          letters: ["t", "a", "n"],
          image: "🟤",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["t.mp3", "a.mp3", "n.mp3", "tan.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L7-WordBuilder-006",
        lesson_number: 7,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "tip",
          letters: ["t", "i", "p"],
          image: "☝️",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["t.mp3", "i.mp3", "p.mp3", "tip.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L7-WordBuilder-007",
        lesson_number: 7,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "nit",
          letters: ["n", "i", "t"],
          image: "🪲",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["n.mp3", "i.mp3", "t.mp3", "nit.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L7-WordBuilder-008",
        lesson_number: 7,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "sip",
          letters: ["s", "i", "p"],
          image: "🥤",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["s.mp3", "i.mp3", "p.mp3", "sip.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L7-WordBuilder-009",
        lesson_number: 7,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "pit",
          letters: ["p", "i", "t"],
          image: "🕳️",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["p.mp3", "i.mp3", "t.mp3", "pit.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L7-WordBuilder-010",
        lesson_number: 7,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "ant",
          letters: ["a", "n", "t"],
          image: "🐜",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["a.mp3", "n.mp3", "t.mp3", "ant.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L7-WordBuilder-011",
        lesson_number: 7,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "nip",
          letters: ["n", "i", "p"],
          image: "🦀",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["n.mp3", "i.mp3", "p.mp3", "nip.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L7-WordBuilder-012",
        lesson_number: 7,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "pan",
          letters: ["p", "a", "n"],
          image: "🍳",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["p.mp3", "a.mp3", "n.mp3", "pan.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
    ],
    story: {
      title: "Nat and Tim",
      text: "Nat sat. Tim sat. Nat and Tim can nap.",
    },
  },
  {
    lesson_number: 8,
    phase: 2,
    title: "New Letters: c, k, d",
    description: "Learn the /k/ sound and /d/ sound",
    new_graphemes: ["c", "k", "d"],
    new_irregular_words: ["is", "his"],
    exercises: [
      {
        exercise_id: "L8-WordBuilder-001",
        lesson_number: 8,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "cat",
          letters: ["c", "a", "t"],
          image: "🐱",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["c.mp3", "a.mp3", "t.mp3", "cat.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L8-WordBuilder-002",
        lesson_number: 8,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "kid",
          letters: ["k", "i", "d"],
          image: "👦",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["k.mp3", "i.mp3", "d.mp3", "kid.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L8-WordBuilder-003",
        lesson_number: 8,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "dad",
          letters: ["d", "a", "d"],
          image: "👨",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["d.mp3", "a.mp3", "d.mp3", "dad.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L8-WordBuilder-004",
        lesson_number: 8,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "can",
          letters: ["c", "a", "n"],
          image: "🥫",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["c.mp3", "a.mp3", "n.mp3", "can.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L8-WordBuilder-005",
        lesson_number: 8,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "kit",
          letters: ["k", "i", "t"],
          image: "🧰",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["k.mp3", "i.mp3", "t.mp3", "kit.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L8-WordBuilder-006",
        lesson_number: 8,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "dip",
          letters: ["d", "i", "p"],
          image: "🍯",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["d.mp3", "i.mp3", "p.mp3", "dip.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L8-WordBuilder-007",
        lesson_number: 8,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "cap",
          letters: ["c", "a", "p"],
          image: "🧢",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["c.mp3", "a.mp3", "p.mp3", "cap.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L8-WordBuilder-008",
        lesson_number: 8,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "dim",
          letters: ["d", "i", "m"],
          image: "🔅",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["d.mp3", "i.mp3", "m.mp3", "dim.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L8-WordBuilder-009",
        lesson_number: 8,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "cot",
          letters: ["c", "o", "t"],
          image: "🛏️",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["c.mp3", "o.mp3", "t.mp3", "cot.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L8-WordBuilder-010",
        lesson_number: 8,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "den",
          letters: ["d", "e", "n"],
          image: "🏠",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["d.mp3", "e.mp3", "n.mp3", "den.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L8-WordBuilder-011",
        lesson_number: 8,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "kid",
          letters: ["k", "i", "d"],
          image: "👦",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["k.mp3", "i.mp3", "d.mp3", "kid.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
      {
        exercise_id: "L8-WordBuilder-012",
        lesson_number: 8,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: {
          word: "cod",
          letters: ["c", "o", "d"],
          image: "🐟",
        },
        response_type: "drag_and_drop",
        assets: { audio: ["c.mp3", "o.mp3", "d.mp3", "cod.mp3"] },
        srs_data: {
          due_date: null,
          stability: 0,
          difficulty: 0,
          review_history: [],
        },
      },
    ],
    story: {
      title: "A cat and a kid",
      text: "A cat sat. A kid can pat the cat. The cat is sad.",
    },
  },
  {
    lesson_number: 9,
    phase: 2,
    title: "New Letters: o, g, h",
    description: "Learn /o/, /g/, and /h/ sounds",
    new_graphemes: ["o", "g", "h"],
    new_irregular_words: ["he", "she"],
    exercises: [
      {
        exercise_id: "L9-WordBuilder-001",
        lesson_number: 9,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "hot", letters: ["h", "o", "t"], image: "🔥" },
        response_type: "drag_and_drop",
        assets: { audio: ["h.mp3", "o.mp3", "t.mp3", "hot.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L9-WordBuilder-002",
        lesson_number: 9,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "dog", letters: ["d", "o", "g"], image: "🐕" },
        response_type: "drag_and_drop",
        assets: { audio: ["d.mp3", "o.mp3", "g.mp3", "dog.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L9-WordBuilder-003",
        lesson_number: 9,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "got", letters: ["g", "o", "t"], image: "✅" },
        response_type: "drag_and_drop",
        assets: { audio: ["g.mp3", "o.mp3", "t.mp3", "got.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L9-WordBuilder-004",
        lesson_number: 9,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "hop", letters: ["h", "o", "p"], image: "🦘" },
        response_type: "drag_and_drop",
        assets: { audio: ["h.mp3", "o.mp3", "p.mp3", "hop.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L9-WordBuilder-005",
        lesson_number: 9,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "hog", letters: ["h", "o", "g"], image: "🐗" },
        response_type: "drag_and_drop",
        assets: { audio: ["h.mp3", "o.mp3", "g.mp3", "hog.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L9-WordBuilder-006",
        lesson_number: 9,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "god", letters: ["g", "o", "d"], image: "⚡" },
        response_type: "drag_and_drop",
        assets: { audio: ["g.mp3", "o.mp3", "d.mp3", "god.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L9-WordBuilder-007",
        lesson_number: 9,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "hog", letters: ["h", "o", "g"], image: "🐗" },
        response_type: "drag_and_drop",
        assets: { audio: ["h.mp3", "o.mp3", "g.mp3", "hog.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L9-WordBuilder-008",
        lesson_number: 9,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "dot", letters: ["d", "o", "t"], image: "⚫" },
        response_type: "drag_and_drop",
        assets: { audio: ["d.mp3", "o.mp3", "t.mp3", "dot.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L9-WordBuilder-009",
        lesson_number: 9,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "hog", letters: ["h", "o", "g"], image: "🐗" },
        response_type: "drag_and_drop",
        assets: { audio: ["h.mp3", "o.mp3", "g.mp3", "hog.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L9-WordBuilder-010",
        lesson_number: 9,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "hog", letters: ["h", "o", "g"], image: "🐗" },
        response_type: "drag_and_drop",
        assets: { audio: ["h.mp3", "o.mp3", "g.mp3", "hog.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "A hot dog", text: "A dog is hot. The dog can hop. He got a hat." },
  },
  {
    lesson_number: 10,
    phase: 2,
    title: "New Letters: b, f, l",
    description: "Learn /b/, /f/, and /l/ sounds",
    new_graphemes: ["b", "f", "l"],
    new_irregular_words: ["of", "was"],
    exercises: [
      {
        exercise_id: "L10-WordBuilder-001",
        lesson_number: 10,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "bat", letters: ["b", "a", "t"], image: "🦇" },
        response_type: "drag_and_drop",
        assets: { audio: ["b.mp3", "a.mp3", "t.mp3", "bat.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L10-WordBuilder-002",
        lesson_number: 10,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "fan", letters: ["f", "a", "n"], image: "🪭" },
        response_type: "drag_and_drop",
        assets: { audio: ["f.mp3", "a.mp3", "n.mp3", "fan.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L10-WordBuilder-003",
        lesson_number: 10,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "lap", letters: ["l", "a", "p"], image: "🧘" },
        response_type: "drag_and_drop",
        assets: { audio: ["l.mp3", "a.mp3", "p.mp3", "lap.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L10-WordBuilder-004",
        lesson_number: 10,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "big", letters: ["b", "i", "g"], image: "🐘" },
        response_type: "drag_and_drop",
        assets: { audio: ["b.mp3", "i.mp3", "g.mp3", "big.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L10-WordBuilder-005",
        lesson_number: 10,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "fit", letters: ["f", "i", "t"], image: "💪" },
        response_type: "drag_and_drop",
        assets: { audio: ["f.mp3", "i.mp3", "t.mp3", "fit.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L10-WordBuilder-006",
        lesson_number: 10,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "log", letters: ["l", "o", "g"], image: "🪵" },
        response_type: "drag_and_drop",
        assets: { audio: ["l.mp3", "o.mp3", "g.mp3", "log.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L10-WordBuilder-007",
        lesson_number: 10,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "bag", letters: ["b", "a", "g"], image: "👜" },
        response_type: "drag_and_drop",
        assets: { audio: ["b.mp3", "a.mp3", "g.mp3", "bag.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L10-WordBuilder-008",
        lesson_number: 10,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "fog", letters: ["f", "o", "g"], image: "🌫️" },
        response_type: "drag_and_drop",
        assets: { audio: ["f.mp3", "o.mp3", "g.mp3", "fog.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L10-WordBuilder-009",
        lesson_number: 10,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "lab", letters: ["l", "a", "b"], image: "🔬" },
        response_type: "drag_and_drop",
        assets: { audio: ["l.mp3", "a.mp3", "b.mp3", "lab.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L10-WordBuilder-010",
        lesson_number: 10,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "fib", letters: ["f", "i", "b"], image: "🤥" },
        response_type: "drag_and_drop",
        assets: { audio: ["f.mp3", "i.mp3", "b.mp3", "fib.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "A big bat", text: "A big bat can fit in a bag. The bat was fat." },
  },
  {
    lesson_number: 11,
    phase: 2,
    title: "New Letters: r, u, j",
    description: "Learn /r/, /u/, and /j/ sounds",
    new_graphemes: ["r", "u", "j"],
    new_irregular_words: ["you", "are"],
    exercises: [
      {
        exercise_id: "L11-WordBuilder-001",
        lesson_number: 11,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "run", letters: ["r", "u", "n"], image: "🏃" },
        response_type: "drag_and_drop",
        assets: { audio: ["r.mp3", "u.mp3", "n.mp3", "run.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L11-WordBuilder-002",
        lesson_number: 11,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "jug", letters: ["j", "u", "g"], image: "🏺" },
        response_type: "drag_and_drop",
        assets: { audio: ["j.mp3", "u.mp3", "g.mp3", "jug.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L11-WordBuilder-003",
        lesson_number: 11,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "rug", letters: ["r", "u", "g"], image: "🧶" },
        response_type: "drag_and_drop",
        assets: { audio: ["r.mp3", "u.mp3", "g.mp3", "rug.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L11-WordBuilder-004",
        lesson_number: 11,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "jam", letters: ["j", "a", "m"], image: "🍓" },
        response_type: "drag_and_drop",
        assets: { audio: ["j.mp3", "a.mp3", "m.mp3", "jam.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L11-WordBuilder-005",
        lesson_number: 11,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "rat", letters: ["r", "a", "t"], image: "🐀" },
        response_type: "drag_and_drop",
        assets: { audio: ["r.mp3", "a.mp3", "t.mp3", "rat.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "Run, run, run", text: "A rat can run. A jug is on a rug. You are big." },
  },
  {
    lesson_number: 12,
    phase: 2,
    title: "New Letters: v, w, x",
    description: "Learn /v/, /w/, and /x/ sounds",
    new_graphemes: ["v", "w", "x"],
    new_irregular_words: ["we", "me"],
    exercises: [
      {
        exercise_id: "L12-WordBuilder-001",
        lesson_number: 12,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "van", letters: ["v", "a", "n"], image: "🚐" },
        response_type: "drag_and_drop",
        assets: { audio: ["v.mp3", "a.mp3", "n.mp3", "van.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L12-WordBuilder-002",
        lesson_number: 12,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "wet", letters: ["w", "e", "t"], image: "💧" },
        response_type: "drag_and_drop",
        assets: { audio: ["w.mp3", "e.mp3", "t.mp3", "wet.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L12-WordBuilder-003",
        lesson_number: 12,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "fox", letters: ["f", "o", "x"], image: "🦊" },
        response_type: "drag_and_drop",
        assets: { audio: ["f.mp3", "o.mp3", "x.mp3", "fox.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L12-WordBuilder-004",
        lesson_number: 12,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "wig", letters: ["w", "i", "g"], image: "💇" },
        response_type: "drag_and_drop",
        assets: { audio: ["w.mp3", "i.mp3", "g.mp3", "wig.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L12-WordBuilder-005",
        lesson_number: 12,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "box", letters: ["b", "o", "x"], image: "📦" },
        response_type: "drag_and_drop",
        assets: { audio: ["b.mp3", "o.mp3", "x.mp3", "box.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "A wet fox", text: "A fox is wet. We can get a box. The fox is in the van." },
  },
  {
    lesson_number: 13,
    phase: 2,
    title: "New Letters: y, z, qu",
    description: "Learn /y/, /z/, and /qu/ sounds",
    new_graphemes: ["y", "z", "qu"],
    new_irregular_words: ["my", "be"],
    exercises: [
      {
        exercise_id: "L13-WordBuilder-001",
        lesson_number: 13,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "yes", letters: ["y", "e", "s"], image: "✅" },
        response_type: "drag_and_drop",
        assets: { audio: ["y.mp3", "e.mp3", "s.mp3", "yes.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L13-WordBuilder-002",
        lesson_number: 13,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "zip", letters: ["z", "i", "p"], image: "🤐" },
        response_type: "drag_and_drop",
        assets: { audio: ["z.mp3", "i.mp3", "p.mp3", "zip.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L13-WordBuilder-003",
        lesson_number: 13,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "quiz", letters: ["qu", "i", "z"], image: "📝" },
        response_type: "drag_and_drop",
        assets: { audio: ["qu.mp3", "i.mp3", "z.mp3", "quiz.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L13-WordBuilder-004",
        lesson_number: 13,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "yam", letters: ["y", "a", "m"], image: "🍠" },
        response_type: "drag_and_drop",
        assets: { audio: ["y.mp3", "a.mp3", "m.mp3", "yam.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L13-WordBuilder-005",
        lesson_number: 13,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "zap", letters: ["z", "a", "p"], image: "⚡" },
        response_type: "drag_and_drop",
        assets: { audio: ["z.mp3", "a.mp3", "p.mp3", "zap.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "My quiz", text: "Yes, I can zip my bag. My quiz is in the bag." },
  },
  {
    lesson_number: 14,
    phase: 2,
    title: "New Letter: e",
    description: "Learn the /e/ sound",
    new_graphemes: ["e"],
    new_irregular_words: ["said", "have"],
    exercises: [
      {
        exercise_id: "L14-WordBuilder-001",
        lesson_number: 14,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "bed", letters: ["b", "e", "d"], image: "🛏️" },
        response_type: "drag_and_drop",
        assets: { audio: ["b.mp3", "e.mp3", "d.mp3", "bed.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L14-WordBuilder-002",
        lesson_number: 14,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "pen", letters: ["p", "e", "n"], image: "🖊️" },
        response_type: "drag_and_drop",
        assets: { audio: ["p.mp3", "e.mp3", "n.mp3", "pen.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L14-WordBuilder-003",
        lesson_number: 14,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "hen", letters: ["h", "e", "n"], image: "🐔" },
        response_type: "drag_and_drop",
        assets: { audio: ["h.mp3", "e.mp3", "n.mp3", "hen.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L14-WordBuilder-004",
        lesson_number: 14,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "leg", letters: ["l", "e", "g"], image: "🦵" },
        response_type: "drag_and_drop",
        assets: { audio: ["l.mp3", "e.mp3", "g.mp3", "leg.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L14-WordBuilder-005",
        lesson_number: 14,
        exercise_type: "Word Builder",
        skill_focus: "CVC Blending",
        data: { word: "net", letters: ["n", "e", "t"], image: "🥅" },
        response_type: "drag_and_drop",
        assets: { audio: ["n.mp3", "e.mp3", "t.mp3", "net.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "A red hen", text: "A red hen is in a pen. The hen said yes. I have a net." },
  },
  {
    lesson_number: 15,
    phase: 2,
    title: "Consonant Digraph: sh",
    description: "Learn the /sh/ sound",
    new_graphemes: ["sh"],
    new_irregular_words: ["they", "all"],
    exercises: [
      {
        exercise_id: "L15-WordBuilder-001",
        lesson_number: 15,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "ship", letters: ["sh", "i", "p"], image: "🚢" },
        response_type: "drag_and_drop",
        assets: { audio: ["sh.mp3", "i.mp3", "p.mp3", "ship.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L15-WordBuilder-002",
        lesson_number: 15,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "shop", letters: ["sh", "o", "p"], image: "🏪" },
        response_type: "drag_and_drop",
        assets: { audio: ["sh.mp3", "o.mp3", "p.mp3", "shop.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L15-WordBuilder-003",
        lesson_number: 15,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "fish", letters: ["f", "i", "sh"], image: "🐟" },
        response_type: "drag_and_drop",
        assets: { audio: ["f.mp3", "i.mp3", "sh.mp3", "fish.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L15-WordBuilder-004",
        lesson_number: 15,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "dish", letters: ["d", "i", "sh"], image: "🍽️" },
        response_type: "drag_and_drop",
        assets: { audio: ["d.mp3", "i.mp3", "sh.mp3", "dish.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L15-WordBuilder-005",
        lesson_number: 15,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "rush", letters: ["r", "u", "sh"], image: "💨" },
        response_type: "drag_and_drop",
        assets: { audio: ["r.mp3", "u.mp3", "sh.mp3", "rush.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "Fish shop", text: "They all rush to the shop. A fish is in a dish." },
  },
  {
    lesson_number: 16,
    phase: 2,
    title: "Consonant Digraph: ch",
    description: "Learn the /ch/ sound",
    new_graphemes: ["ch"],
    new_irregular_words: ["some", "come"],
    exercises: [
      {
        exercise_id: "L16-WordBuilder-001",
        lesson_number: 16,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "chip", letters: ["ch", "i", "p"], image: "🍟" },
        response_type: "drag_and_drop",
        assets: { audio: ["ch.mp3", "i.mp3", "p.mp3", "chip.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L16-WordBuilder-002",
        lesson_number: 16,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "chat", letters: ["ch", "a", "t"], image: "💬" },
        response_type: "drag_and_drop",
        assets: { audio: ["ch.mp3", "a.mp3", "t.mp3", "chat.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L16-WordBuilder-003",
        lesson_number: 16,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "much", letters: ["m", "u", "ch"], image: "📊" },
        response_type: "drag_and_drop",
        assets: { audio: ["m.mp3", "u.mp3", "ch.mp3", "much.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L16-WordBuilder-004",
        lesson_number: 16,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "chop", letters: ["ch", "o", "p"], image: "🪓" },
        response_type: "drag_and_drop",
        assets: { audio: ["ch.mp3", "o.mp3", "p.mp3", "chop.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L16-WordBuilder-005",
        lesson_number: 16,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "rich", letters: ["r", "i", "ch"], image: "💰" },
        response_type: "drag_and_drop",
        assets: { audio: ["r.mp3", "i.mp3", "ch.mp3", "rich.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "Chip chat", text: "Come and chat. I have some chips. They are rich." },
  },
  {
    lesson_number: 17,
    phase: 2,
    title: "Consonant Digraph: th",
    description: "Learn the /th/ sound",
    new_graphemes: ["th"],
    new_irregular_words: ["there", "were"],
    exercises: [
      {
        exercise_id: "L17-WordBuilder-001",
        lesson_number: 17,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "this", letters: ["th", "i", "s"], image: "👈" },
        response_type: "drag_and_drop",
        assets: { audio: ["th.mp3", "i.mp3", "s.mp3", "this.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L17-WordBuilder-002",
        lesson_number: 17,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "that", letters: ["th", "a", "t"], image: "👉" },
        response_type: "drag_and_drop",
        assets: { audio: ["th.mp3", "a.mp3", "t.mp3", "that.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L17-WordBuilder-003",
        lesson_number: 17,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "path", letters: ["p", "a", "th"], image: "🛤️" },
        response_type: "drag_and_drop",
        assets: { audio: ["p.mp3", "a.mp3", "th.mp3", "path.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L17-WordBuilder-004",
        lesson_number: 17,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "with", letters: ["w", "i", "th"], image: "🤝" },
        response_type: "drag_and_drop",
        assets: { audio: ["w.mp3", "i.mp3", "th.mp3", "with.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L17-WordBuilder-005",
        lesson_number: 17,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "bath", letters: ["b", "a", "th"], image: "🛁" },
        response_type: "drag_and_drop",
        assets: { audio: ["b.mp3", "a.mp3", "th.mp3", "bath.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "This path", text: "This is a path. There were baths with that." },
  },
  {
    lesson_number: 18,
    phase: 2,
    title: "Consonant Digraph: wh, ng",
    description: "Learn the /wh/ and /ng/ sounds",
    new_graphemes: ["wh", "ng"],
    new_irregular_words: ["what", "when"],
    exercises: [
      {
        exercise_id: "L18-WordBuilder-001",
        lesson_number: 18,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "when", letters: ["wh", "e", "n"], image: "⏰" },
        response_type: "drag_and_drop",
        assets: { audio: ["wh.mp3", "e.mp3", "n.mp3", "when.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L18-WordBuilder-002",
        lesson_number: 18,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "ring", letters: ["r", "i", "ng"], image: "💍" },
        response_type: "drag_and_drop",
        assets: { audio: ["r.mp3", "i.mp3", "ng.mp3", "ring.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L18-WordBuilder-003",
        lesson_number: 18,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "sing", letters: ["s", "i", "ng"], image: "🎤" },
        response_type: "drag_and_drop",
        assets: { audio: ["s.mp3", "i.mp3", "ng.mp3", "sing.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L18-WordBuilder-004",
        lesson_number: 18,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "bang", letters: ["b", "a", "ng"], image: "💥" },
        response_type: "drag_and_drop",
        assets: { audio: ["b.mp3", "a.mp3", "ng.mp3", "bang.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L18-WordBuilder-005",
        lesson_number: 18,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "king", letters: ["k", "i", "ng"], image: "👑" },
        response_type: "drag_and_drop",
        assets: { audio: ["k.mp3", "i.mp3", "ng.mp3", "king.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "When the king sings", text: "What is that? When the king sings, the ring goes bang!" },
  },
  {
    lesson_number: 19,
    phase: 2,
    title: "Consonant Digraph: ck",
    description: "Learn the /ck/ spelling pattern",
    new_graphemes: ["ck"],
    new_irregular_words: ["little", "one"],
    exercises: [
      {
        exercise_id: "L19-WordBuilder-001",
        lesson_number: 19,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "duck", letters: ["d", "u", "ck"], image: "🦆" },
        response_type: "drag_and_drop",
        assets: { audio: ["d.mp3", "u.mp3", "ck.mp3", "duck.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L19-WordBuilder-002",
        lesson_number: 19,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "sock", letters: ["s", "o", "ck"], image: "🧦" },
        response_type: "drag_and_drop",
        assets: { audio: ["s.mp3", "o.mp3", "ck.mp3", "sock.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L19-WordBuilder-003",
        lesson_number: 19,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "lock", letters: ["l", "o", "ck"], image: "🔒" },
        response_type: "drag_and_drop",
        assets: { audio: ["l.mp3", "o.mp3", "ck.mp3", "lock.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L19-WordBuilder-004",
        lesson_number: 19,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "pick", letters: ["p", "i", "ck"], image: "☝️" },
        response_type: "drag_and_drop",
        assets: { audio: ["p.mp3", "i.mp3", "ck.mp3", "pick.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L19-WordBuilder-005",
        lesson_number: 19,
        exercise_type: "Word Builder",
        skill_focus: "Digraph Blending",
        data: { word: "back", letters: ["b", "a", "ck"], image: "⬅️" },
        response_type: "drag_and_drop",
        assets: { audio: ["b.mp3", "a.mp3", "ck.mp3", "back.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "One little duck", text: "One little duck can pick a sock. The duck is back with a lock." },
  },
  {
    lesson_number: 20,
    phase: 2,
    title: "Double Letters: ff, ll, ss",
    description: "Learn double consonant patterns",
    new_graphemes: ["ff", "ll", "ss"],
    new_irregular_words: ["do", "so"],
    exercises: [
      {
        exercise_id: "L20-WordBuilder-001",
        lesson_number: 20,
        exercise_type: "Word Builder",
        skill_focus: "Double Consonant Blending",
        data: { word: "puff", letters: ["p", "u", "ff"], image: "💨" },
        response_type: "drag_and_drop",
        assets: { audio: ["p.mp3", "u.mp3", "ff.mp3", "puff.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L20-WordBuilder-002",
        lesson_number: 20,
        exercise_type: "Word Builder",
        skill_focus: "Double Consonant Blending",
        data: { word: "bell", letters: ["b", "e", "ll"], image: "🔔" },
        response_type: "drag_and_drop",
        assets: { audio: ["b.mp3", "e.mp3", "ll.mp3", "bell.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L20-WordBuilder-003",
        lesson_number: 20,
        exercise_type: "Word Builder",
        skill_focus: "Double Consonant Blending",
        data: { word: "miss", letters: ["m", "i", "ss"], image: "🎯" },
        response_type: "drag_and_drop",
        assets: { audio: ["m.mp3", "i.mp3", "ss.mp3", "miss.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L20-WordBuilder-004",
        lesson_number: 20,
        exercise_type: "Word Builder",
        skill_focus: "Double Consonant Blending",
        data: { word: "doll", letters: ["d", "o", "ll"], image: "🪆" },
        response_type: "drag_and_drop",
        assets: { audio: ["d.mp3", "o.mp3", "ll.mp3", "doll.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L20-WordBuilder-005",
        lesson_number: 20,
        exercise_type: "Word Builder",
        skill_focus: "Double Consonant Blending",
        data: { word: "pass", letters: ["p", "a", "ss"], image: "✅" },
        response_type: "drag_and_drop",
        assets: { audio: ["p.mp3", "a.mp3", "ss.mp3", "pass.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "Do not miss", text: "Do not miss the bell. So the doll can pass with a puff." },
  },
  {
    lesson_number: 21,
    phase: 2,
    title: "Consonant Blends: bl, cl, fl",
    description: "Learn initial L-blends",
    new_graphemes: ["bl", "cl", "fl"],
    new_irregular_words: ["like", "out"],
    exercises: [
      {
        exercise_id: "L21-WordBuilder-001",
        lesson_number: 21,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "blue", letters: ["bl", "ue"], image: "🔵" },
        response_type: "drag_and_drop",
        assets: { audio: ["bl.mp3", "ue.mp3", "blue.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L21-WordBuilder-002",
        lesson_number: 21,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "clap", letters: ["cl", "a", "p"], image: "👏" },
        response_type: "drag_and_drop",
        assets: { audio: ["cl.mp3", "a.mp3", "p.mp3", "clap.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L21-WordBuilder-003",
        lesson_number: 21,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "flag", letters: ["fl", "a", "g"], image: "🚩" },
        response_type: "drag_and_drop",
        assets: { audio: ["fl.mp3", "a.mp3", "g.mp3", "flag.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L21-WordBuilder-004",
        lesson_number: 21,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "club", letters: ["cl", "u", "b"], image: "♣️" },
        response_type: "drag_and_drop",
        assets: { audio: ["cl.mp3", "u.mp3", "b.mp3", "club.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L21-WordBuilder-005",
        lesson_number: 21,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "flip", letters: ["fl", "i", "p"], image: "🔄" },
        response_type: "drag_and_drop",
        assets: { audio: ["fl.mp3", "i.mp3", "p.mp3", "flip.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "Blue flag", text: "I like the blue flag. Clap and flip out the club." },
  },
  {
    lesson_number: 22,
    phase: 2,
    title: "Consonant Blends: pl, sl, gl",
    description: "Learn more initial L-blends",
    new_graphemes: ["pl", "sl", "gl"],
    new_irregular_words: ["look", "good"],
    exercises: [
      {
        exercise_id: "L22-WordBuilder-001",
        lesson_number: 22,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "plan", letters: ["pl", "a", "n"], image: "📋" },
        response_type: "drag_and_drop",
        assets: { audio: ["pl.mp3", "a.mp3", "n.mp3", "plan.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L22-WordBuilder-002",
        lesson_number: 22,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "slip", letters: ["sl", "i", "p"], image: "🧊" },
        response_type: "drag_and_drop",
        assets: { audio: ["sl.mp3", "i.mp3", "p.mp3", "slip.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L22-WordBuilder-003",
        lesson_number: 22,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "glad", letters: ["gl", "a", "d"], image: "😊" },
        response_type: "drag_and_drop",
        assets: { audio: ["gl.mp3", "a.mp3", "d.mp3", "glad.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L22-WordBuilder-004",
        lesson_number: 22,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "plus", letters: ["pl", "u", "s"], image: "➕" },
        response_type: "drag_and_drop",
        assets: { audio: ["pl.mp3", "u.mp3", "s.mp3", "plus.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L22-WordBuilder-005",
        lesson_number: 22,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "slug", letters: ["sl", "u", "g"], image: "🐌" },
        response_type: "drag_and_drop",
        assets: { audio: ["sl.mp3", "u.mp3", "g.mp3", "slug.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "Good plan", text: "Look at the good plan. The glad slug can slip plus." },
  },
  {
    lesson_number: 23,
    phase: 2,
    title: "Consonant Blends: br, cr, dr",
    description: "Learn initial R-blends",
    new_graphemes: ["br", "cr", "dr"],
    new_irregular_words: ["down", "now"],
    exercises: [
      {
        exercise_id: "L23-WordBuilder-001",
        lesson_number: 23,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "brag", letters: ["br", "a", "g"], image: "💪" },
        response_type: "drag_and_drop",
        assets: { audio: ["br.mp3", "a.mp3", "g.mp3", "brag.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L23-WordBuilder-002",
        lesson_number: 23,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "crab", letters: ["cr", "a", "b"], image: "🦀" },
        response_type: "drag_and_drop",
        assets: { audio: ["cr.mp3", "a.mp3", "b.mp3", "crab.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L23-WordBuilder-003",
        lesson_number: 23,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "drop", letters: ["dr", "o", "p"], image: "💧" },
        response_type: "drag_and_drop",
        assets: { audio: ["dr.mp3", "o.mp3", "p.mp3", "drop.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L23-WordBuilder-004",
        lesson_number: 23,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "crop", letters: ["cr", "o", "p"], image: "🌾" },
        response_type: "drag_and_drop",
        assets: { audio: ["cr.mp3", "o.mp3", "p.mp3", "crop.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L23-WordBuilder-005",
        lesson_number: 23,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "drum", letters: ["dr", "u", "m"], image: "🥁" },
        response_type: "drag_and_drop",
        assets: { audio: ["dr.mp3", "u.mp3", "m.mp3", "drum.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "Crab drops down", text: "Now the crab drops down. The drum can brag with the crop." },
  },
  {
    lesson_number: 24,
    phase: 2,
    title: "Consonant Blends: fr, gr, pr, tr",
    description: "Learn more initial R-blends",
    new_graphemes: ["fr", "gr", "pr", "tr"],
    new_irregular_words: ["from", "them"],
    exercises: [
      {
        exercise_id: "L24-WordBuilder-001",
        lesson_number: 24,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "frog", letters: ["fr", "o", "g"], image: "🐸" },
        response_type: "drag_and_drop",
        assets: { audio: ["fr.mp3", "o.mp3", "g.mp3", "frog.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L24-WordBuilder-002",
        lesson_number: 24,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "grab", letters: ["gr", "a", "b"], image: "✊" },
        response_type: "drag_and_drop",
        assets: { audio: ["gr.mp3", "a.mp3", "b.mp3", "grab.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L24-WordBuilder-003",
        lesson_number: 24,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "trip", letters: ["tr", "i", "p"], image: "🧳" },
        response_type: "drag_and_drop",
        assets: { audio: ["tr.mp3", "i.mp3", "p.mp3", "trip.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L24-WordBuilder-004",
        lesson_number: 24,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "grin", letters: ["gr", "i", "n"], image: "😁" },
        response_type: "drag_and_drop",
        assets: { audio: ["gr.mp3", "i.mp3", "n.mp3", "grin.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L24-WordBuilder-005",
        lesson_number: 24,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "from", letters: ["fr", "o", "m"], image: "➡️" },
        response_type: "drag_and_drop",
        assets: { audio: ["fr.mp3", "o.mp3", "m.mp3", "from.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "Frog trip", text: "The frog can grab them. From the trip, the frog can grin." },
  },
  {
    lesson_number: 25,
    phase: 2,
    title: "Consonant Blends: sc, sk, sm, sn, sp, st, sw",
    description: "Learn initial S-blends",
    new_graphemes: ["sc", "sk", "sm", "sn", "sp", "st", "sw"],
    new_irregular_words: ["into", "could"],
    exercises: [
      {
        exercise_id: "L25-WordBuilder-001",
        lesson_number: 25,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "skip", letters: ["sk", "i", "p"], image: "🦘" },
        response_type: "drag_and_drop",
        assets: { audio: ["sk.mp3", "i.mp3", "p.mp3", "skip.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L25-WordBuilder-002",
        lesson_number: 25,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "snap", letters: ["sn", "a", "p"], image: "📸" },
        response_type: "drag_and_drop",
        assets: { audio: ["sn.mp3", "a.mp3", "p.mp3", "snap.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L25-WordBuilder-003",
        lesson_number: 25,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "stop", letters: ["st", "o", "p"], image: "🛑" },
        response_type: "drag_and_drop",
        assets: { audio: ["st.mp3", "o.mp3", "p.mp3", "stop.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L25-WordBuilder-004",
        lesson_number: 25,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "swim", letters: ["sw", "i", "m"], image: "🏊" },
        response_type: "drag_and_drop",
        assets: { audio: ["sw.mp3", "i.mp3", "m.mp3", "swim.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
      {
        exercise_id: "L25-WordBuilder-005",
        lesson_number: 25,
        exercise_type: "Word Builder",
        skill_focus: "Consonant Blend",
        data: { word: "spin", letters: ["sp", "i", "n"], image: "🌀" },
        response_type: "drag_and_drop",
        assets: { audio: ["sp.mp3", "i.mp3", "n.mp3", "spin.mp3"] },
        srs_data: { due_date: null, stability: 0, difficulty: 0, review_history: [] },
      },
    ],
    story: { title: "Skip and swim", text: "Skip into the swim. Stop and snap. I could spin." },
  },
];
